/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.AreaDAO;
import datos.ClienteDAO;
import datos.ContratoDAO;
import datos.EmpresaDAO;
import datos.EspacioDAO;
import datos.ParqueaderoDAO;
import datos.RegistroDAO;
import datos.TarifaDAO;
import datos.VehiculoDAO;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.Area;
import negocio.Cliente;
import negocio.Contrato;
import negocio.Empresa;
import negocio.Espacio;
import negocio.Registro;
import negocio.Parqueadero;
import negocio.Tarifa;
import negocio.Vehiculo;
import util.CaException;

/**
 *
 * @author Sebas
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Pago
     */
    Contrato contrato = new Contrato();
    Vehiculo vehiculo = new Vehiculo();
    Registro registro = new Registro();
    Cliente cliente = new Cliente();
    Area area = new Area();
    Empresa empresa = new Empresa();
    Espacio espacio = new Espacio();
    Parqueadero pq = new Parqueadero();
    Tarifa tarifa = new Tarifa();

    AreaDAO area_dao = new AreaDAO();
    ClienteDAO cliente_dao = new ClienteDAO();
    ContratoDAO contrato_dao = new ContratoDAO();
    EmpresaDAO empresa_dao = new EmpresaDAO();
    EspacioDAO espacio_dao = new EspacioDAO();
    ParqueaderoDAO pq_dao = new ParqueaderoDAO();
    RegistroDAO registro_dao = new RegistroDAO();
    TarifaDAO tarifa_dao = new TarifaDAO();
    VehiculoDAO vh_dao = new VehiculoDAO();

    Calendar c1 = Calendar.getInstance();

    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtBox1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtBox2 = new javax.swing.JTextField();
        TxtBox3 = new javax.swing.JTextField();
        TxtBox4 = new javax.swing.JTextField();
        ButtonConsulta = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtBox5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxTabla = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("K_IdA");

        TxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cupo");

        jLabel3.setText("N_Tipo");

        jLabel4.setText("K_IdE");

        TxtBox4.setOpaque(false);
        TxtBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox4ActionPerformed(evt);
            }
        });

        ButtonConsulta.setText("Consulta");
        ButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultaActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor pago");

        TxtBox5.setOpaque(false);
        TxtBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("CONSULTAS Y MODIFICACIONES");

        ComboBoxTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Area", "Cliente", "Contrato", "Empresa", "Espacio", "Parqueadero", "Registro", "Tarifa", "Vehiculo" }));
        ComboBoxTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTablaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tabla a usar:");

        ButtonModificar.setText("Modificar");
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonConsulta)
                        .addGap(55, 55, 55)
                        .addComponent(ButtonModificar)
                        .addGap(48, 48, 48)
                        .addComponent(ButtonEliminar)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5))
                                            .addGap(134, 134, 134)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TxtBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                    .addComponent(TxtBox3)
                                                    .addComponent(TxtBox4, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonConsulta)
                    .addComponent(ButtonEliminar)
                    .addComponent(ButtonModificar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox1ActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        String temp = ComboBoxTabla.getSelectedItem().toString();

        try {
            if (temp == "Area") {
                area.setK_IdA(Integer.parseInt(TxtBox1.getText()));
                area_dao.setArea(area);
                area_dao.eliminarArea();

                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Cliente") {
                cliente.setK_Cc(Integer.parseInt(TxtBox1.getText()));
                cliente_dao.setCliente(cliente);
                cliente_dao.eliminarCliente();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Contrato") {
                contrato.setK_NumCont(Integer.parseInt(TxtBox1.getText()));
                contrato_dao.setContrato(contrato);
                contrato_dao.eliminarContrato();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Empresa") {
                empresa.setK_Nit(Integer.parseInt(TxtBox1.getText()));
                empresa_dao.setEmpresa(empresa);
                empresa_dao.eliminarEmpresa();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Espacio") {
                espacio.setK_IdE(Integer.parseInt(TxtBox1.getText()));
                espacio_dao.setEspacio(espacio);
                espacio_dao.eliminarEspacio();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Parqueadero") {
                pq.setK_Id(Integer.parseInt(TxtBox1.getText()));
                pq_dao.setPq(pq);
                pq_dao.eliminarParqueadero();

                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Registro") {
                registro.setK_CONSECUTIVO(Integer.parseInt(TxtBox1.getText()));
                registro_dao.setRegistro(registro);
                registro_dao.eliminarRegistro();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Tarifa") {
                tarifa.setK_IdT(Integer.parseInt(TxtBox1.getText()));
                tarifa_dao.setTarifa(tarifa);
                tarifa_dao.eliminarTarifa();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Vehiculo") {
                vehiculo.setK_Placa(TxtBox1.getText());
                vh_dao.setVehiculo(vehiculo);
                vh_dao.eliminarVehiculo();
                TxtBox1.setText("");
                TxtBox2.setText("");
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            }

        } catch (CaException ex) {
            Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void ButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultaActionPerformed
        String temp = ComboBoxTabla.getSelectedItem().toString();

        try {

            if (temp == "Area") {
                area.setK_IdA(Integer.parseInt(TxtBox1.getText()));
                area_dao.setArea(area);
                area_dao.buscarArea();
                area = area_dao.getArea();
                TxtBox1.setText(Integer.toString(area.getK_IdA()));
                TxtBox2.setText(Integer.toString(area.getCupo()));
                TxtBox3.setText(area.getN_Tipo());
                TxtBox4.setText(Integer.toString(area.getK_IdE()));
                TxtBox5.setText("");
            } else if (temp == "Cliente") {
                cliente.setK_Cc(Integer.parseInt(TxtBox1.getText()));
                cliente_dao.setCliente(cliente);
                cliente_dao.buscarCliente();
                cliente = cliente_dao.getCliente();
                TxtBox1.setText(Integer.toString(cliente.getK_Cc()));
                TxtBox2.setText(cliente.getN_Nombre());
                TxtBox3.setText(cliente.getK_Telefono());
                TxtBox4.setText(cliente.getCorreo());
                TxtBox5.setText(Integer.toString(cliente.getK_NumCont()));
            } else if (temp == "Contrato") {
                contrato.setK_NumCont(Integer.parseInt(TxtBox1.getText()));
                contrato_dao.setContrato(contrato);
                contrato_dao.buscarContrato();
                contrato = contrato_dao.getContrato();
                TxtBox1.setText(Integer.toString(contrato.getK_NumCont()));
                TxtBox2.setText(contrato.getTipoV());
                TxtBox3.setText(contrato.getF_Inicio());
                TxtBox4.setText(contrato.getF_Final());
                TxtBox5.setText(Integer.toString(contrato.getValor()));
            } else if (temp == "Empresa") {
                empresa.setK_Nit(Integer.parseInt(TxtBox1.getText()));
                empresa_dao.setEmpresa(empresa);
                empresa_dao.buscarEmpresa();
                empresa = empresa_dao.getEmpresa();
                TxtBox1.setText(Integer.toString(empresa.getK_Nit()));
                TxtBox2.setText(empresa.getRSocial());
                TxtBox3.setText(Integer.toString(empresa.getK_IdP()));
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Espacio") {
                espacio.setK_IdE(Integer.parseInt(TxtBox1.getText()));
                espacio_dao.setEspacio(espacio);
                espacio_dao.buscarEspacio();
                espacio = espacio_dao.getEspacio();
                TxtBox1.setText(Integer.toString(espacio.getK_IdE()));
                TxtBox2.setText(Integer.toString(espacio.getDisponible()));
                TxtBox3.setText(Integer.toString(espacio.getK_NumCont()));
                TxtBox4.setText(Integer.toString(espacio.getConse_Reg()));
                TxtBox5.setText("");
            } else if (temp == "Parqueadero") {
                pq.setK_Id(Integer.parseInt(TxtBox1.getText()));
                pq_dao.setPq(pq);
                pq_dao.buscarParqueadero();
                pq = pq_dao.getPq();
                TxtBox1.setText(Integer.toString(pq.getK_Id()));
                TxtBox2.setText(pq.getN_Zona());
                TxtBox3.setText(Integer.toString(pq.getN_Tipo()));
                TxtBox4.setText(Integer.toString(pq.getK_IdA()));
                TxtBox5.setText(Integer.toString(pq.getK_IdT()));
            } else if (temp == "Registro") {
                registro.setK_CONSECUTIVO(Integer.parseInt(TxtBox1.getText()));
                registro_dao.setRegistro(registro);
                registro_dao.eliminarRegistro();
                registro = registro_dao.getRegistro();
                TxtBox1.setText(Integer.toString(registro.getK_CONSECUTIVO()));
                TxtBox2.setText(registro.getF_HEntrada());
                TxtBox3.setText(registro.getF_HSalida());
                TxtBox4.setText(Integer.toString(registro.getTotal()));
                TxtBox5.setText(registro.getK_Placa());
            } else if (temp == "Tarifa") {
                tarifa.setK_IdT(Integer.parseInt(TxtBox1.getText()));
                tarifa_dao.setTarifa(tarifa);
                tarifa_dao.eliminarTarifa();
                tarifa = tarifa_dao.getTarifa();
                TxtBox1.setText(Integer.toString(tarifa.getK_IdT()));
                TxtBox2.setText(Double.toString(tarifa.getValor()));
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Vehiculo") {
                vehiculo.setK_Placa(TxtBox1.getText());
                vh_dao.setVehiculo(vehiculo);
                vh_dao.buscarVehiculo();
                vehiculo = vh_dao.getVehiculo();
                TxtBox1.setText(vehiculo.getK_Placa());
                TxtBox2.setText(vehiculo.getN_Marca());
                TxtBox3.setText(vehiculo.getN_Modelo());
                TxtBox4.setText(vehiculo.getTipoVeh());
                TxtBox5.setText("");
            }

        } catch (CaException ex) {
            Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonConsultaActionPerformed

    private void TxtBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox4ActionPerformed

    private void TxtBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox5ActionPerformed

    private void ComboBoxTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTablaActionPerformed
        String temp = ComboBoxTabla.getSelectedItem().toString();
        if (temp == "Area") {
            jLabel1.setText("K_IdA");
            jLabel2.setText("Cupo");
            jLabel3.setText("N_Tipo");
            jLabel4.setText("K_IdE");
            jLabel5.setText("");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(false);

        } else if (temp == "Cliente") {
            jLabel1.setText("K_Cc");
            jLabel2.setText("N_Nombre");
            jLabel3.setText("K_Telefono");
            jLabel4.setText("Correo");
            jLabel5.setText("K_NumCont");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(true);

        } else if (temp == "Contrato") {
            jLabel1.setText("K_NumCont");
            jLabel2.setText("TipoV");
            jLabel3.setText("F_Inicio");
            jLabel4.setText("F_Final");
            jLabel5.setText("Valor");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(true);

        } else if (temp == "Empresa") {
            jLabel1.setText("K_Nit");
            jLabel2.setText("RSocial");
            jLabel3.setText("K_IdP");
            jLabel4.setText("");
            jLabel5.setText("");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(false);
            TxtBox5.setVisible(false);

        } else if (temp == "Espacio") {
            jLabel1.setText("K_IdE");
            jLabel2.setText("disponible");
            jLabel3.setText("K_NumCont");
            jLabel4.setText("conse_Reg");
            jLabel5.setText("");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(false);

        } else if (temp == "Parqueadero") {
            jLabel1.setText("K_Id");
            jLabel2.setText("N_Zona");
            jLabel3.setText("N_Tipo");
            jLabel4.setText("K_IdA");
            jLabel5.setText("K_IdT");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(true);

        } else if (temp == "Registro") {
            jLabel1.setText("K_CONSECUTIVO");
            jLabel2.setText("F_HEntrada");
            jLabel3.setText("F_HSalida");
            jLabel4.setText("Total");
            jLabel5.setText("K_Placa");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(true);

        } else if (temp == "Tarifa") {
            jLabel1.setText("K_IdT");
            jLabel2.setText("valor");
            jLabel3.setText("");
            jLabel4.setText("");
            jLabel5.setText("");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(false);
            TxtBox4.setVisible(false);
            TxtBox5.setVisible(false);

        } else if (temp == "Vehiculo") {
            jLabel1.setText("K_Placa");
            jLabel2.setText("N_Marca");
            jLabel3.setText("K_Modelo");
            jLabel4.setText("Tipoveh");
            jLabel5.setText("");
            TxtBox1.setText("");
            TxtBox2.setText("");
            TxtBox3.setText("");
            TxtBox4.setText("");
            TxtBox5.setText("");

            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            TxtBox1.setVisible(true);
            TxtBox2.setVisible(true);
            TxtBox3.setVisible(true);
            TxtBox4.setVisible(true);
            TxtBox5.setVisible(false);

        }
    }//GEN-LAST:event_ComboBoxTablaActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        String temp = ComboBoxTabla.getSelectedItem().toString();
        try {
            if (temp == "Area") {
                area.setK_IdA(Integer.parseInt(TxtBox1.getText()));
                area_dao.setArea(area);
                area_dao.buscarArea();
                area = area_dao.getArea();
                TxtBox1.setText(Integer.toString(area.getK_IdA()));
                TxtBox2.setText(Integer.toString(area.getCupo()));
                TxtBox3.setText(area.getN_Tipo());
                TxtBox4.setText(Integer.toString(area.getK_IdE()));
                TxtBox5.setText("");
            } else if (temp == "Cliente") {
                cliente.setK_Cc(Integer.parseInt(TxtBox1.getText()));
                cliente_dao.setCliente(cliente);
                cliente_dao.buscarCliente();
                cliente = cliente_dao.getCliente();
                TxtBox1.setText(Integer.toString(cliente.getK_Cc()));
                TxtBox2.setText(cliente.getN_Nombre());
                TxtBox3.setText(cliente.getK_Telefono());
                TxtBox4.setText(cliente.getCorreo());
                TxtBox5.setText(Integer.toString(cliente.getK_NumCont()));
            } else if (temp == "Contrato") {
                contrato.setK_NumCont(Integer.parseInt(TxtBox1.getText()));
                contrato.setTipoV(TxtBox2.getText());
                contrato.setF_Inicio(TxtBox3.getText());
                contrato.setF_Final(TxtBox4.getText());
                contrato.setValor(Integer.parseInt(TxtBox5.getText()));
                contrato_dao.setContrato(contrato);
                contrato_dao.modificarContrato();
              
            } else if (temp == "Empresa") {
                empresa.setK_Nit(Integer.parseInt(TxtBox1.getText()));
                empresa_dao.setEmpresa(empresa);
                empresa_dao.buscarEmpresa();
                empresa = empresa_dao.getEmpresa();
                TxtBox1.setText(Integer.toString(empresa.getK_Nit()));
                TxtBox2.setText(empresa.getRSocial());
                TxtBox3.setText(Integer.toString(empresa.getK_IdP()));
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Espacio") {
                espacio.setK_IdE(Integer.parseInt(TxtBox1.getText()));
                espacio_dao.setEspacio(espacio);
                espacio_dao.buscarEspacio();
                espacio = espacio_dao.getEspacio();
                TxtBox1.setText(Integer.toString(espacio.getK_IdE()));
                TxtBox2.setText(Integer.toString(espacio.getDisponible()));
                TxtBox3.setText(Integer.toString(espacio.getK_NumCont()));
                TxtBox4.setText(Integer.toString(espacio.getConse_Reg()));
                TxtBox5.setText("");
            } else if (temp == "Parqueadero") {
                pq.setK_Id(Integer.parseInt(TxtBox1.getText()));
                pq_dao.setPq(pq);
                pq_dao.buscarParqueadero();
                pq = pq_dao.getPq();
                TxtBox1.setText(Integer.toString(pq.getK_Id()));
                TxtBox2.setText(pq.getN_Zona());
                TxtBox3.setText(Integer.toString(pq.getN_Tipo()));
                TxtBox4.setText(Integer.toString(pq.getK_IdA()));
                TxtBox5.setText(Integer.toString(pq.getK_IdT()));
            } else if (temp == "Registro") {
                registro.setK_CONSECUTIVO(Integer.parseInt(TxtBox1.getText()));
                registro_dao.setRegistro(registro);
                registro_dao.eliminarRegistro();
                registro = registro_dao.getRegistro();
                TxtBox1.setText(Integer.toString(registro.getK_CONSECUTIVO()));
                TxtBox2.setText(registro.getF_HEntrada());
                TxtBox3.setText(registro.getF_HSalida());
                TxtBox4.setText(Integer.toString(registro.getTotal()));
                TxtBox5.setText(registro.getK_Placa());
            } else if (temp == "Tarifa") {
                tarifa.setK_IdT(Integer.parseInt(TxtBox1.getText()));
                tarifa_dao.setTarifa(tarifa);
                tarifa_dao.eliminarTarifa();
                tarifa = tarifa_dao.getTarifa();
                TxtBox1.setText(Integer.toString(tarifa.getK_IdT()));
                TxtBox2.setText(Double.toString(tarifa.getValor()));
                TxtBox3.setText("");
                TxtBox4.setText("");
                TxtBox5.setText("");
            } else if (temp == "Vehiculo") {
                vehiculo.setK_Placa(TxtBox1.getText());
                vh_dao.setVehiculo(vehiculo);
                vh_dao.buscarVehiculo();
                vehiculo = vh_dao.getVehiculo();
                TxtBox1.setText(vehiculo.getK_Placa());
                TxtBox2.setText(vehiculo.getN_Marca());
                TxtBox3.setText(vehiculo.getN_Modelo());
                TxtBox4.setText(vehiculo.getTipoVeh());
                TxtBox5.setText("");
            }
        }catch (CaException ex) {
            Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsulta;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JComboBox<String> ComboBoxTabla;
    private javax.swing.JTextField TxtBox1;
    private javax.swing.JTextField TxtBox2;
    private javax.swing.JTextField TxtBox3;
    private javax.swing.JTextField TxtBox4;
    private javax.swing.JTextField TxtBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}


/*
Vehiculo vehiculo = new Vehiculo();
        vehiculo.setK_Placa(LabelPago.getText());
        
        Contrato contrato = new Contrato();
        contrato.setF_Inicio(LabelHoraE.getText());
        contrato.setF_Final(LabelHoraS.getText());
        
        Tarifa tarifa = new Tarifa();
        tarifa.setValor(Integer.parseInt(LabelPago.getText()));
 */
