/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.ClienteDAO;
import datos.ContratoDAO;
import datos.RegistroDAO;
import datos.VehiculoDAO;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Cliente;
import negocio.Contrato;
import negocio.Registro;
import negocio.Vehiculo;
import util.CaException;

/**
 *
 * @author Sebas
 */
public class PRQ extends javax.swing.JFrame {

    /**
     * Creates new form Parqueadero
     */
    public PRQ() {
        initComponents();
    }
    Contrato contrato = new Contrato();
    Vehiculo vehiculo = new Vehiculo();
    Registro registro = new Registro();
    Cliente cliente = new Cliente();
    ClienteDAO cliente_dao = new ClienteDAO();
    ContratoDAO contrato_dao = new ContratoDAO();
    RegistroDAO registro_dao = new RegistroDAO();
    VehiculoDAO vh_dao= new VehiculoDAO();
    Calendar c1 = Calendar.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBox1 = new javax.swing.JTextField();
        ButtonIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        TxtBox2 = new javax.swing.JTextField();
        TxtBox3 = new javax.swing.JTextField();
        LabelEntrada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtBox4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtBox5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtBox6 = new javax.swing.JTextField();
        ComboBoxEntrada = new javax.swing.JComboBox<>();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtBox7 = new javax.swing.JTextField();
        TxtBox8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox1ActionPerformed(evt);
            }
        });

        ButtonIngresar.setText("Ingresar");
        ButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Contrato");

        jLabel2.setText("Fecha Inicio");

        jLabel3.setText("Fecha Final");

        LabelTipo.setText("Tipo de vehiculo");

        TxtBox2.setText("dd//MM/yyyy");
        TxtBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox2ActionPerformed(evt);
            }
        });

        TxtBox3.setText("dd/MM/YYYY");
        TxtBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox3ActionPerformed(evt);
            }
        });

        LabelEntrada.setText("Entrada tipo");

        jLabel4.setText("Valor");

        TxtBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cedula del cliente");

        TxtBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtBox5MouseEntered(evt);
            }
        });
        TxtBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre");

        TxtBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox6ActionPerformed(evt);
            }
        });

        ComboBoxEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contrato", "Registro unico" }));
        ComboBoxEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEntradaActionPerformed(evt);
            }
        });

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Moto" }));

        jLabel7.setText("Teléfono");

        jLabel8.setText("Correo");

        TxtBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox7ActionPerformed(evt);
            }
        });

        TxtBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(ButtonIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LabelEntrada)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelTipo)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBox4)
                            .addComponent(TxtBox5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(TxtBox6)
                            .addComponent(TxtBox7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addComponent(TxtBox8))))
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ComboBoxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelEntrada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTipo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonIngresar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox2ActionPerformed

    private void TxtBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox5ActionPerformed

    private void TxtBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox6ActionPerformed

    private void TxtBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBox5MouseEntered

    }//GEN-LAST:event_TxtBox5MouseEntered

    private void ComboBoxEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEntradaActionPerformed
        String temp = ComboBoxEntrada.getSelectedItem().toString();
        if (temp == "Contrato") {
            jLabel1.setText("Numero de contrato");
            jLabel2.setText("Fecha de Inicio");
            jLabel3.setText("Fecha Final");
            jLabel4.setText("Valor");
            jLabel5.setText("Cédula del cliente");
            jLabel6.setText("Nombre");
            jLabel7.setText("Teléfono");
            jLabel8.setText("Correo");
            TxtBox2.setText("dd/MM/yyyy");
            TxtBox3.setText("dd/MM/yyyy");
            TxtBox2.setEnabled(true);
            TxtBox6.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);

            TxtBox7.setVisible(true);
            TxtBox8.setVisible(true);

        } else if (temp == "Registro unico") {
            jLabel1.setText("Consecutivo");
            jLabel2.setText("Fecha de Inicio");
            jLabel3.setText("Placa");
            jLabel4.setText("Marca");
            jLabel5.setText("Modelo");
            
            TxtBox1.setText("");
            TxtBox2.setText(Integer.toString(c1.get(Calendar.HOUR))+":"+Integer.toString(c1.get(Calendar.MINUTE)));
            TxtBox3.setText("");
            TxtBox2.setEnabled(false);
            TxtBox6.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);

            TxtBox7.setVisible(false);
            TxtBox8.setVisible(false);

        }
    }//GEN-LAST:event_ComboBoxEntradaActionPerformed

    private void TxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox1ActionPerformed

    private void TxtBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox4ActionPerformed

    private void TxtBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox8ActionPerformed

    private void TxtBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox7ActionPerformed

    private void ButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarActionPerformed

        try {

            if (ComboBoxEntrada.getSelectedItem().toString().equals("Contrato")) {
                contrato.setK_NumCont(Integer.parseInt(TxtBox1.getText()));
                contrato.setTipoV(ComboBoxEntrada.getSelectedItem().toString());
                contrato.setF_Inicio(TxtBox2.getText());
                contrato.setF_Final(TxtBox3.getText());
                contrato.setValor(Integer.parseInt(TxtBox4.getText()));
                contrato_dao.setContrato(contrato);
                contrato_dao.incluirContrato();

                cliente.setK_Cc(Integer.parseInt(TxtBox5.getText()));
                cliente.setN_Nombre(TxtBox6.getText());
                cliente.setK_Telefono(TxtBox7.getText());
                cliente.setCorreo(TxtBox8.getText());
                cliente.setK_NumCont(Integer.parseInt(TxtBox1.getText()));
                cliente_dao.setCliente(cliente);
                cliente_dao.incluirCliente();                
            } else {
                registro.setK_CONSECUTIVO(Integer.parseInt(TxtBox1.getText()));
                registro.setF_HEntrada(TxtBox2.getText());
                registro.setF_HSalida(null);
                registro.setTotal(0);
                registro.setK_Placa(TxtBox3.getText());
                registro_dao.setRegistro(registro);
                registro_dao.incluirRegistro();
                
                vehiculo.setK_Placa(TxtBox3.getText());
                vehiculo.setN_Marca(TxtBox4.getText());
                vehiculo.setN_Modelo(TxtBox5.getText());
                vehiculo.setTipoVeh(ComboBoxEntrada.getSelectedItem().toString());
                vh_dao.setVehiculo(vehiculo);
                vh_dao.incluirVehiculo();              
            }
        } catch (CaException ex) {
            Logger.getLogger(PRQ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonIngresarActionPerformed

    private void TxtBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngresar;
    private javax.swing.JComboBox<String> ComboBoxEntrada;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JLabel LabelEntrada;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JTextField TxtBox1;
    private javax.swing.JTextField TxtBox2;
    private javax.swing.JTextField TxtBox3;
    private javax.swing.JTextField TxtBox4;
    private javax.swing.JTextField TxtBox5;
    private javax.swing.JTextField TxtBox6;
    private javax.swing.JTextField TxtBox7;
    private javax.swing.JTextField TxtBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
